#!/usr/bin/expect -f
set timeout -1
spawn ./st2
expect "Enter keyring passphrase:"
send -- "YOUR_KEYRING_PPHRSEp\r"
send -- "y\r"
expect "Enter keyring passphrase:"
send -- "YOUR_KEYRING_PPHRSE\r"
send -- "y\r"
expect eof
